### ISSUE TITLE
LNK2005: "virtual struct vgi::dbconn::dbi::istatement * __thiscall vgi::dbconn::dbd::sybase::connection::get_statement(struct vgi::dbconn::dbi::iconnection &)" already defined

### ISSUE THREAD

**Issue by Eggache666** [vimsh/db_conn#1]
This is a very good cpp api for sybase, it works well in single cpp file, but when i include "sybase_driver.hpp" into a header file 'a.h', and an other file include the file 'a.h'。When complie&link the project, a link error has occurred:

------------------------------------
LNK2005: "virtual struct vgi::dbconn::dbi::istatement * __thiscall vgi::dbconn::dbd::sybase::connection::get_statement(struct vgi::dbconn::dbi::iconnection &)" already defined
-------------------------------------

It seems to point to the end of the file sybase_driver.hpp:

dbi::istatement* connection::get_statement(dbi::iconnection& iconn)
{
    return new statement(dynamic_cast<connection&>(iconn));
}

So， how to solve the problem? Thank you!
------------------------------------------------------------------------------------
I separate this function from the file to a .cpp file, and then add all this files to project.
This can solve the link error.

**Comment by vimsh** [comment]
The concrete driver implementations are not meant to be included in header files. You should be including only generic classes header files. Actually, just driver.hpp would do as it will include all the other files. And only in your .cpp files you would include a concrete driver header file.

**Comment by Eggache666** [comment]
You gave me some very good methods, I will try it again. Thank you very much!!!
